parameters:
    es.logging.path: "%kernel.logs_dir%/elasticsearch_%kernel.environment%.log"

services:

    _defaults:
        public: true
        autowire: true

    ONGR\ElasticsearchBundle\Command\:
        resource: '../../Command'
        tags:
            - { name: console.command }

    ongr.esb.cache_adapter:
        class: Symfony\Component\Cache\Adapter\PhpFilesAdapter
        arguments: ['elasticsearch', 0, "%kernel.cache_dir%/ongr", false]

    ongr.esb.cache:
        class: Doctrine\Common\Cache\Psr6\DoctrineProvider
        factory: ['Doctrine\Common\Cache\Psr6\DoctrineProvider', 'wrap']
        arguments: ["@ongr.esb.cache_adapter"]

    ongr.esb.cache_reader:
        class: Doctrine\Common\Annotations\PsrCachedReader
        arguments: ["@annotations.reader", "@ongr.esb.cache_adapter", "%kernel.debug%"]

    ONGR\ElasticsearchBundle\Service\ExportService: ~
    ONGR\ElasticsearchBundle\Service\ImportService: ~
    ONGR\ElasticsearchBundle\Service\IndexSuffixFinder: ~
    ONGR\ElasticsearchBundle\Mapping\Converter: ~

    ONGR\ElasticsearchBundle\Mapping\DocumentParser:
        arguments: ["@ongr.esb.cache_reader", "@ongr.esb.cache", "%ongr.esb.analysis%"]

    ONGR\ElasticsearchBundle\Profiler\Handler\CollectionHandler:
        public: false

    ongr.esb.tracer:
        class: Monolog\Logger
        arguments: ['ongr']
        calls:
            - [pushHandler, ['@ONGR\ElasticsearchBundle\Profiler\Handler\CollectionHandler']]

    ONGR\ElasticsearchBundle\Profiler\ElasticsearchProfiler:
        calls:
            - [setIndexes, ["%ongr.esb.indexes%"]]
            - [addLogger, ["@ongr.esb.tracer"]]
        tags:
            - {name: data_collector, template: "@ONGRElasticsearch/Profiler/profiler.html.twig", id: ongr.profiler}

    ONGR\ElasticsearchBundle\EventListener\TerminateListener:
        arguments: ["@service_container", "%ongr.esb.indexes%"]
        tags:
            - { name: kernel.event_listener, event: kernel.terminate }
